---
- hosts: win-servers
  tasks:
  - name: Install Chrome
    win_chocolatey:
      name: googlechrome
      state: present

  - name: install all critical and security updates
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      - Application
      - UpdateRollups
      - Updates
      - Tools
      - DefinitionUpdates
      - Connectors
      - FeaturePacks
      state: installed
    register: update_result

  - name: reboot host if required
    win_reboot:
    when: update_result.reboot_required
